# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: 🚀 Deploy Build and Baraka API

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: 🏗️ Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Deploy to VPS
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/scrumizy/backend
            git pull origin main
            docker-compose down --remove-orphans || true
            docker-compose up -d --build
            sleep 20
            curl -f http://localhost:4001/ && echo "✅ Deployment successful!" || echo "❌ Deployment failed!"
